apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: $CLUSTER_ISSUER
  namespace: cert-manager
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: $CATENA_ADMIN_MAIL
    privateKeySecretRef:
      name: $CLIENT_ISSUER
    solvers:
    - http01:
        ingress:
          class: nginx
          podTemplate:
            spec:
              nodeSelector:
                "kubernetes.io/os": linux